SELECT EMP_NAME, JOB_CODE, DEPT_CODE,SALARY
FROM EMPLOYEE E
WHERE SALARY >= (SELECT AVG(SALARY) FROM  EMPLOYEE);

SELECT EMP_NAME,JOB_CODE,DEPT_CODE,SALARY
FROM EMPLOYEE
WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE);

select *
from employee
where email like '%k%@%';

select COUNT(*) ,SUBSTR(PHONE,1,3)
from employee
where substr(PHONE,1,3) IN ('010','011')
GROUP BY SUBSTR(PHONE,1,3);

SELECT DEPT_CODE,COUNT(*)
FROM EMPLOYEE, DEPARTMENT
WHERE MANAGER_ID IS NULL;

SELECT DEPT_CODE,EMP_ID,EMP_NAME
FROM EMPLOYEE
WHERE MANAGER_ID IS NULL;

SELECT DEPT_TITLE,DEPT_CODE,EMP_ID,EMP_NAME
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID AND MANAGER_ID IS NULL;

SELECT DEPT_TITLE,DEPT_CODE,EMP_ID,EMP_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE MANAGER_ID IS NULL;

SELECT DEPT_TITLE, COUNT(*)
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID AND MANAGER_ID IS NULL
GROUP BY DEPT_TITLE;

SELECT DEPT_TITLE, COUNT(*)
FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
WHERE MANAGER_ID IS NULL
GROUP BY DEPT_TITLE;

